# Generated by Django 2.1.1 on 2019-01-20 20:33

import django.core.validators
from django.db import migrations, models
import musicTeacher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null=True, upload_to='photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('surname', models.CharField(default='<фамилия>', max_length=128)),
                ('name', models.CharField(default='<имя>', max_length=128)),
                ('patronymic', models.CharField(default='<отчество>', max_length=128)),
                ('position', models.CharField(default='<должность>', max_length=255)),
                ('greeting', models.CharField(default='<приветствие>', max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('document', models.FileField(upload_to='papers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('pub_date', models.DateTimeField(editable=False, verbose_name='date published')),
                ('upd_date', models.DateTimeField(editable=False, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('pub_date', models.DateTimeField(editable=False, verbose_name='date published')),
                ('upd_date', models.DateTimeField(editable=False, verbose_name='date updated')),
                ('is_achievement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('url', models.URLField(validators=[musicTeacher.validators.validate_youtube_url])),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='sheets_folder',
        ),
        migrations.AddField(
            model_name='music',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='music',
            name='sheets',
            field=models.FileField(blank=True, null=True, upload_to='sheets/sheets', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'rar', 'zip', '7z'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='sheets/audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mid', 'midi'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='pub_date',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='music',
            name='upd_date',
            field=models.DateTimeField(editable=False, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='paper',
            name='photos',
            field=models.ManyToManyField(to='musicTeacher.Photo'),
        ),
        migrations.AddField(
            model_name='paper',
            name='videos',
            field=models.ManyToManyField(to='musicTeacher.Video'),
        ),
    ]
