# Generated by Django 2.2 on 2019-04-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0002_auto_20190120_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
