# Generated by Django 2.2 on 2019-04-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0003_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicTeacher.MainPageInfo'),
        ),
    ]
