# Generated by Django 2.2 on 2019-05-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0004_citation_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='when',
            field=models.DateTimeField(null=True, verbose_name='date of photo'),
        ),
    ]
