# Generated by Django 2.2 on 2019-05-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0005_photo_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='short_descr',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
