# Generated by Django 2.2 on 2019-05-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicTeacher', '0006_auto_20190510_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of photo'),
        ),
    ]
